### ISSUE TITLE
Allow user's to choose their own categories

### ISSUE THREAD

**Issue by YaManicKill** [pokemontrades/flairhq#565]
This would stop people complaining about the names of the categories, and I think it's something we should probably do at some point.

**Comment by DerekC15** [comment]
If not allowing users to make their own categories, at least make a new set of categories, the same ones we already have, but for Gen 7, and have everything that's already there go to a Gen 6 section. Then there wouldn't be complicated (I assume) coding that allows custom names and such. Plus, having users make their own categories would just make it harder to find a certain trade/link again, since everyone organizes things differently. Everything is already really nicely organized, good for Gen 3-5 things too, which I feel should stay in. It's just getting a tiniest bit annoying for me, to, if/when it shows up in the future, I'll have to transfer over whatever Gen 7 trades I've done onto a new section. Which, by then, will more than likely be a decent amount.

Nothing's wrong with what the categories are. I just think that there should be more categories, for different Gens. In this case, one for Gen 3-5, one for Gen 6 (what we have now), and one for Gen 7 (duplicating Gen 6's categories).

~ PikaCuber

**Comment by YaManicKill** [comment]
> If not allowing users to make their own categories, at least make a new set of categories, the same ones we already have, but for Gen 7, and have everything that's already there go to a Gen 6 section.

This is why I want custom categories, because it's pissing annoying adding new categories everytime we think of something, every new gen, etc.

And everyone will have different ideas about what we should have, and what  they want theirs to look like.

I, for one, don't want that many categories, that's a lot of categories.

**Comment by DerekC15** [comment]
I suppose that's fair. Then again, if there are custom categories, I personally would probably just copy the exact same format that's there now. I only don't like custom categories due to issues with finding other trades perhaps, or looking at other people's flairHQ.

~PikaCuber
