### ISSUE TITLE
Change to emoji-based flair system

### ISSUE THREAD

**Issue by robdy** [pokemontrades/flairhq#646]
I'll drop here the notes about what we need to switch to emoji-based user flair:

- For background compatibility add in the stylesheet: 

      span.flairbase.flairrichtext.flair {height: 30px; color: #555555 !important}
      span.flairemoji {height: 30px; width: 30px}
- .... (will add later)

**Comment by McInkay** [comment]
Is this how the new system works in reddit?

**Comment by SnowPhoenix** [comment]
Yeah, images in flair are handled as "emoji" in new Reddit. That's what the update I've been working on is for. The code for handling them on old Reddit has already been added to the CSS.

**Comment by McInkay** [comment]
Ok, cool. So adding this should be easy to be backwards compatible if it's already on the CSS then. I presume it's a different API call? Almost entirely backend changes, right? I guess we'll probably want to change the frontend to use the same as the css on the sub as well though

**Comment by pkmnbumba** [comment]
Just to add, looks like we need to move on from using css_class for emojis if we want flairs to show up. Did some minor testing, and it looks like as long as we have emojis in the correct format (:emoji:), then it'll show up on the Reddit App, redesign, and old reddit. css_class is only used for old reddit.

Browsers on mobile won't display (instead it will show up as :text:), but its better than nothing displaying at all.

We'll have to update:

- [ ] AutoModerator to using flair_text (includes): rather than css_class (includes)
- [ ] How FHQ sets flairs to only use flair_text (at least for flairs)

**Comment by Raia** [comment]
@pkmnbumba I don't think we should get rid of `css_class` support entirely. We should preserve the functionality for old Reddit, and I think the CSS class should be the main source of truth if there is ever any discrepancy between a user's CSS flair class and what they have in their text.

**Comment by pkmnbumba** [comment]
Adding here from discussion today that css_class takes precedence over flair_text (not really relevant to what is programmed in FHQ, but could be useful knowledge for later)
